"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.report_account_ids import ReportAccountIds
from openapi_client.model.report_custom_fields import ReportCustomFields
globals()['ReportAccountIds'] = ReportAccountIds
globals()['ReportCustomFields'] = ReportCustomFields
from openapi_client.model.voa_with_income_report_constraints_out import VOAWithIncomeReportConstraintsOut


class TestVOAWithIncomeReportConstraintsOut(unittest.TestCase):
    """VOAWithIncomeReportConstraintsOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVOAWithIncomeReportConstraintsOut(self):
        """Test VOAWithIncomeReportConstraintsOut"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VOAWithIncomeReportConstraintsOut()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
