"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.report_account_ids import ReportAccountIds
from openapi_client.model.report_custom_fields import ReportCustomFields
globals()['ReportAccountIds'] = ReportAccountIds
globals()['ReportCustomFields'] = ReportCustomFields
from openapi_client.model.voe_transactions_report_constraints_out import VOETransactionsReportConstraintsOut


class TestVOETransactionsReportConstraintsOut(unittest.TestCase):
    """VOETransactionsReportConstraintsOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVOETransactionsReportConstraintsOut(self):
        """Test VOETransactionsReportConstraintsOut"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VOETransactionsReportConstraintsOut()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
