"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.created_customer import CreatedCustomer


class TestCreatedCustomer(unittest.TestCase):
    """CreatedCustomer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreatedCustomer(self):
        """Test CreatedCustomer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreatedCustomer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
