"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.base_report_ack_with_portfolio_id import BaseReportAckWithPortfolioId
from openapi_client.model.cash_flow_cash_flow_balance_summary import CashFlowCashFlowBalanceSummary
from openapi_client.model.cash_flow_cash_flow_characteristics_summary import CashFlowCashFlowCharacteristicsSummary
from openapi_client.model.cash_flow_cash_flow_credit_summary import CashFlowCashFlowCreditSummary
from openapi_client.model.cash_flow_cash_flow_debit_summary import CashFlowCashFlowDebitSummary
from openapi_client.model.cash_flow_possible_loan_deposits import CashFlowPossibleLoanDeposits
from openapi_client.model.cash_flow_report_all_of import CashFlowReportAllOf
from openapi_client.model.error_message import ErrorMessage
from openapi_client.model.report_institution import ReportInstitution
globals()['BaseReportAckWithPortfolioId'] = BaseReportAckWithPortfolioId
globals()['CashFlowCashFlowBalanceSummary'] = CashFlowCashFlowBalanceSummary
globals()['CashFlowCashFlowCharacteristicsSummary'] = CashFlowCashFlowCharacteristicsSummary
globals()['CashFlowCashFlowCreditSummary'] = CashFlowCashFlowCreditSummary
globals()['CashFlowCashFlowDebitSummary'] = CashFlowCashFlowDebitSummary
globals()['CashFlowPossibleLoanDeposits'] = CashFlowPossibleLoanDeposits
globals()['CashFlowReportAllOf'] = CashFlowReportAllOf
globals()['ErrorMessage'] = ErrorMessage
globals()['ReportInstitution'] = ReportInstitution
from openapi_client.model.cash_flow_report import CashFlowReport


class TestCashFlowReport(unittest.TestCase):
    """CashFlowReport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCashFlowReport(self):
        """Test CashFlowReport"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CashFlowReport()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
