"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.cash_flow_activity_deposits_credits import CashFlowActivityDepositsCredits
from openapi_client.model.cash_flow_activity_withdrawals_debits import CashFlowActivityWithdrawalsDebits
from openapi_client.model.cash_flow_num_weeks_zeros import CashFlowNumWeeksZeros
from openapi_client.model.cash_flow_transaction_analytics_attributes_last_transaction_date import CashFlowTransactionAnalyticsAttributesLastTransactionDate
from openapi_client.model.obb_date_range_and_amount import ObbDateRangeAndAmount
globals()['CashFlowActivityDepositsCredits'] = CashFlowActivityDepositsCredits
globals()['CashFlowActivityWithdrawalsDebits'] = CashFlowActivityWithdrawalsDebits
globals()['CashFlowNumWeeksZeros'] = CashFlowNumWeeksZeros
globals()['CashFlowTransactionAnalyticsAttributesLastTransactionDate'] = CashFlowTransactionAnalyticsAttributesLastTransactionDate
globals()['ObbDateRangeAndAmount'] = ObbDateRangeAndAmount
from openapi_client.model.cash_flow_transaction_analytics_attributes import CashFlowTransactionAnalyticsAttributes


class TestCashFlowTransactionAnalyticsAttributes(unittest.TestCase):
    """CashFlowTransactionAnalyticsAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCashFlowTransactionAnalyticsAttributes(self):
        """Test CashFlowTransactionAnalyticsAttributes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CashFlowTransactionAnalyticsAttributes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
