"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.portfolios_api import PortfoliosApi  # noqa: E501


class TestPortfoliosApi(unittest.TestCase):
    """PortfoliosApi unit test stubs"""

    def setUp(self):
        self.api = PortfoliosApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_portfolio_by_consumer(self):
        """Test case for get_portfolio_by_consumer

        Get Portfolio by Consumer  # noqa: E501
        """
        pass

    def test_get_portfolio_by_customer(self):
        """Test case for get_portfolio_by_customer

        Get Portfolio by Customer  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
