"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.third_party_access_proof import ThirdPartyAccessProof
from openapi_client.model.third_party_access_receipt import ThirdPartyAccessReceipt
globals()['ThirdPartyAccessProof'] = ThirdPartyAccessProof
globals()['ThirdPartyAccessReceipt'] = ThirdPartyAccessReceipt
from openapi_client.model.third_party_access_receipt_data import ThirdPartyAccessReceiptData


class TestThirdPartyAccessReceiptData(unittest.TestCase):
    """ThirdPartyAccessReceiptData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testThirdPartyAccessReceiptData(self):
        """Test ThirdPartyAccessReceiptData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ThirdPartyAccessReceiptData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
