"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.report_income_stream_summary import ReportIncomeStreamSummary
from openapi_client.model.report_institution import ReportInstitution
globals()['ReportIncomeStreamSummary'] = ReportIncomeStreamSummary
globals()['ReportInstitution'] = ReportInstitution
from openapi_client.model.voi_report_all_of import VOIReportAllOf


class TestVOIReportAllOf(unittest.TestCase):
    """VOIReportAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVOIReportAllOf(self):
        """Test VOIReportAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VOIReportAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
