"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.accounts__simple_api import AccountsSimpleApi  # noqa: E501


class TestAccountsSimpleApi(unittest.TestCase):
    """AccountsSimpleApi unit test stubs"""

    def setUp(self):
        self.api = AccountsSimpleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_customer_account_simple(self):
        """Test case for get_customer_account_simple

        Get Customer Account by ID (Simple)  # noqa: E501
        """
        pass

    def test_get_customer_accounts_by_institution_login_simple(self):
        """Test case for get_customer_accounts_by_institution_login_simple

        Get Customer Accounts by Institution Login ID (Simple)  # noqa: E501
        """
        pass

    def test_get_customer_accounts_by_institution_simple(self):
        """Test case for get_customer_accounts_by_institution_simple

        Get Customer Accounts by Institution ID (Simple)  # noqa: E501
        """
        pass

    def test_get_customer_accounts_simple(self):
        """Test case for get_customer_accounts_simple

        Get Customer Accounts (Simple)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
