"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.balance_analytics_account_result import BalanceAnalyticsAccountResult
from openapi_client.model.balance_analytics_business_summary import BalanceAnalyticsBusinessSummary
from openapi_client.model.obb_report_header import ObbReportHeader
globals()['BalanceAnalyticsAccountResult'] = BalanceAnalyticsAccountResult
globals()['BalanceAnalyticsBusinessSummary'] = BalanceAnalyticsBusinessSummary
globals()['ObbReportHeader'] = ObbReportHeader
from openapi_client.model.balance_analytics_report import BalanceAnalyticsReport


class TestBalanceAnalyticsReport(unittest.TestCase):
    """BalanceAnalyticsReport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBalanceAnalyticsReport(self):
        """Test BalanceAnalyticsReport"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BalanceAnalyticsReport()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
