"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.deductions import Deductions
from openapi_client.model.direct_deposits import DirectDeposits
from openapi_client.model.earnings import Earnings
from openapi_client.model.main_pay_statement_fields import MainPayStatementFields
globals()['Deductions'] = Deductions
globals()['DirectDeposits'] = DirectDeposits
globals()['Earnings'] = Earnings
globals()['MainPayStatementFields'] = MainPayStatementFields
from openapi_client.model.direct_pay_statements import DirectPayStatements


class TestDirectPayStatements(unittest.TestCase):
    """DirectPayStatements unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDirectPayStatements(self):
        """Test DirectPayStatements"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DirectPayStatements()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
