"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.account_details_tx_based import AccountDetailsTxBased
from openapi_client.model.cash_flow_cash_flow_balance import CashFlowCashFlowBalance
from openapi_client.model.cash_flow_cash_flow_characteristic import CashFlowCashFlowCharacteristic
from openapi_client.model.cash_flow_cash_flow_credit import CashFlowCashFlowCredit
from openapi_client.model.cash_flow_cash_flow_debit import CashFlowCashFlowDebit
from openapi_client.model.cash_flow_report_account import CashFlowReportAccount
from openapi_client.model.prequalification_report_account import PrequalificationReportAccount
from openapi_client.model.prequalification_report_asset_summary import PrequalificationReportAssetSummary
from openapi_client.model.report_account_position import ReportAccountPosition
from openapi_client.model.report_transaction import ReportTransaction
from openapi_client.model.report_transaction_new_tx_based import ReportTransactionNewTxBased
from openapi_client.model.transactions_report_account import TransactionsReportAccount
from openapi_client.model.voa_report_account import VOAReportAccount
from openapi_client.model.voa_with_income_report_account import VOAWithIncomeReportAccount
from openapi_client.model.voe_transactions_report_account import VOETransactionsReportAccount
from openapi_client.model.voi_report_account import VOIReportAccount
from openapi_client.model.voietx_verify_report_account import VOIETXVerifyReportAccount
from openapi_client.model.voietx_verify_report_income_stream import VOIETXVerifyReportIncomeStream
globals()['AccountDetailsTxBased'] = AccountDetailsTxBased
globals()['CashFlowCashFlowBalance'] = CashFlowCashFlowBalance
globals()['CashFlowCashFlowCharacteristic'] = CashFlowCashFlowCharacteristic
globals()['CashFlowCashFlowCredit'] = CashFlowCashFlowCredit
globals()['CashFlowCashFlowDebit'] = CashFlowCashFlowDebit
globals()['CashFlowReportAccount'] = CashFlowReportAccount
globals()['PrequalificationReportAccount'] = PrequalificationReportAccount
globals()['PrequalificationReportAssetSummary'] = PrequalificationReportAssetSummary
globals()['ReportAccountPosition'] = ReportAccountPosition
globals()['ReportTransaction'] = ReportTransaction
globals()['ReportTransactionNewTxBased'] = ReportTransactionNewTxBased
globals()['TransactionsReportAccount'] = TransactionsReportAccount
globals()['VOAReportAccount'] = VOAReportAccount
globals()['VOAWithIncomeReportAccount'] = VOAWithIncomeReportAccount
globals()['VOETransactionsReportAccount'] = VOETransactionsReportAccount
globals()['VOIETXVerifyReportAccount'] = VOIETXVerifyReportAccount
globals()['VOIETXVerifyReportIncomeStream'] = VOIETXVerifyReportIncomeStream
globals()['VOIReportAccount'] = VOIReportAccount
from openapi_client.model.report_institution_account import ReportInstitutionAccount


class TestReportInstitutionAccount(unittest.TestCase):
    """ReportInstitutionAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReportInstitutionAccount(self):
        """Test ReportInstitutionAccount"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ReportInstitutionAccount()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
