"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.cadence_details import CadenceDetails
from openapi_client.model.net_monthly import NetMonthly
from openapi_client.model.report_transaction import ReportTransaction
globals()['CadenceDetails'] = CadenceDetails
globals()['NetMonthly'] = NetMonthly
globals()['ReportTransaction'] = ReportTransaction
from openapi_client.model.voi_report_income_stream import VOIReportIncomeStream


class TestVOIReportIncomeStream(unittest.TestCase):
    """VOIReportIncomeStream unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVOIReportIncomeStream(self):
        """Test VOIReportIncomeStream"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VOIReportIncomeStream()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
