"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.base_report_ack_with_portfolio_id import BaseReportAckWithPortfolioId
from openapi_client.model.error_message import ErrorMessage
from openapi_client.model.prequalification_report_asset_summary import PrequalificationReportAssetSummary
from openapi_client.model.report_institution import ReportInstitution
from openapi_client.model.voa_report_all_of import VOAReportAllOf
globals()['BaseReportAckWithPortfolioId'] = BaseReportAckWithPortfolioId
globals()['ErrorMessage'] = ErrorMessage
globals()['PrequalificationReportAssetSummary'] = PrequalificationReportAssetSummary
globals()['ReportInstitution'] = ReportInstitution
globals()['VOAReportAllOf'] = VOAReportAllOf
from openapi_client.model.voa_with_income_report import VOAWithIncomeReport


class TestVOAWithIncomeReport(unittest.TestCase):
    """VOAWithIncomeReport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVOAWithIncomeReport(self):
        """Test VOAWithIncomeReport"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VOAWithIncomeReport()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
