"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.report_transaction_base1 import ReportTransactionBase1
from openapi_client.model.report_transaction_base2 import ReportTransactionBase2
from openapi_client.model.report_transaction_new_tx_based_all_of import ReportTransactionNewTxBasedAllOf
globals()['ReportTransactionBase1'] = ReportTransactionBase1
globals()['ReportTransactionBase2'] = ReportTransactionBase2
globals()['ReportTransactionNewTxBasedAllOf'] = ReportTransactionNewTxBasedAllOf
from openapi_client.model.report_transaction_new_tx_based import ReportTransactionNewTxBased


class TestReportTransactionNewTxBased(unittest.TestCase):
    """ReportTransactionNewTxBased unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReportTransactionNewTxBased(self):
        """Test ReportTransactionNewTxBased"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ReportTransactionNewTxBased()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
