"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.report_custom_fields import ReportCustomFields
from openapi_client.model.statement_data import StatementData
globals()['ReportCustomFields'] = ReportCustomFields
globals()['StatementData'] = StatementData
from openapi_client.model.statement_report_constraints import StatementReportConstraints


class TestStatementReportConstraints(unittest.TestCase):
    """StatementReportConstraints unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatementReportConstraints(self):
        """Test StatementReportConstraints"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StatementReportConstraints()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
