"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.branding import Branding
from openapi_client.model.institution_address import InstitutionAddress
globals()['Branding'] = Branding
globals()['InstitutionAddress'] = InstitutionAddress
from openapi_client.model.institution import Institution


class TestInstitution(unittest.TestCase):
    """Institution unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstitution(self):
        """Test Institution"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Institution()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
