"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.account_owner_addresses import AccountOwnerAddresses
from openapi_client.model.account_owner_documentations import AccountOwnerDocumentations
from openapi_client.model.account_owner_emails import AccountOwnerEmails
from openapi_client.model.account_owner_identity_insights import AccountOwnerIdentityInsights
from openapi_client.model.account_owner_phones import AccountOwnerPhones
globals()['AccountOwnerAddresses'] = AccountOwnerAddresses
globals()['AccountOwnerDocumentations'] = AccountOwnerDocumentations
globals()['AccountOwnerEmails'] = AccountOwnerEmails
globals()['AccountOwnerIdentityInsights'] = AccountOwnerIdentityInsights
globals()['AccountOwnerPhones'] = AccountOwnerPhones
from openapi_client.model.account_owner_details import AccountOwnerDetails


class TestAccountOwnerDetails(unittest.TestCase):
    """AccountOwnerDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountOwnerDetails(self):
        """Test AccountOwnerDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountOwnerDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
