"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.cash_flow_cash_flow_balance import CashFlowCashFlowBalance
from openapi_client.model.cash_flow_cash_flow_characteristic import CashFlowCashFlowCharacteristic
from openapi_client.model.cash_flow_cash_flow_credit import CashFlowCashFlowCredit
from openapi_client.model.cash_flow_cash_flow_debit import CashFlowCashFlowDebit
from openapi_client.model.report_transaction import ReportTransaction
globals()['CashFlowCashFlowBalance'] = CashFlowCashFlowBalance
globals()['CashFlowCashFlowCharacteristic'] = CashFlowCashFlowCharacteristic
globals()['CashFlowCashFlowCredit'] = CashFlowCashFlowCredit
globals()['CashFlowCashFlowDebit'] = CashFlowCashFlowDebit
globals()['ReportTransaction'] = ReportTransaction
from openapi_client.model.cash_flow_report_account import CashFlowReportAccount


class TestCashFlowReportAccount(unittest.TestCase):
    """CashFlowReportAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCashFlowReportAccount(self):
        """Test CashFlowReportAccount"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CashFlowReportAccount()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
