"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.assets_api import AssetsApi  # noqa: E501


class TestAssetsApi(unittest.TestCase):
    """AssetsApi unit test stubs"""

    def setUp(self):
        self.api = AssetsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_asset_by_customer_id(self):
        """Test case for get_asset_by_customer_id

        Get Asset by Customer and ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
