"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.paystub_tx_verify_monthly_income_record import PaystubTxVerifyMonthlyIncomeRecord
globals()['PaystubTxVerifyMonthlyIncomeRecord'] = PaystubTxVerifyMonthlyIncomeRecord
from openapi_client.model.voie_paystub_with_statement_pay_statement_all_of import VOIEPaystubWithStatementPayStatementAllOf


class TestVOIEPaystubWithStatementPayStatementAllOf(unittest.TestCase):
    """VOIEPaystubWithStatementPayStatementAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVOIEPaystubWithStatementPayStatementAllOf(self):
        """Test VOIEPaystubWithStatementPayStatementAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VOIEPaystubWithStatementPayStatementAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
