"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)
from ..model_utils import OpenApiModel
from openapi_client.exceptions import ApiAttributeError


def lazy_import():
    from openapi_client.model.payroll_employer_address import PayrollEmployerAddress
    globals()['PayrollEmployerAddress'] = PayrollEmployerAddress


class PayrollEmploymentRecord(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'employer_name': (str,),  # noqa: E501
            'employment_status_code': (str,),  # noqa: E501
            'employment_status_name': (str,),  # noqa: E501
            'work_level_status': (str,),  # noqa: E501
            'legal_entity_id': (str,),  # noqa: E501
            'original_hire_date': (int,),  # noqa: E501
            'latest_hire_date': (int,),  # noqa: E501
            'latest_pay_date': (int,),  # noqa: E501
            'days_since_last_pay': (int,),  # noqa: E501
            'number_pay_cadence_without_pay': (int,),  # noqa: E501
            'employment_end_date': (int,),  # noqa: E501
            'employment_duration': (str,),  # noqa: E501
            'employer_address': ([PayrollEmployerAddress],),  # noqa: E501
            'work_level_code': (str,),  # noqa: E501
            'work_level_name': (str,),  # noqa: E501
            'position_title': (str,),  # noqa: E501
            'position_duration': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'employer_name': 'employerName',  # noqa: E501
        'employment_status_code': 'employmentStatusCode',  # noqa: E501
        'employment_status_name': 'employmentStatusName',  # noqa: E501
        'work_level_status': 'workLevelStatus',  # noqa: E501
        'legal_entity_id': 'legalEntityId',  # noqa: E501
        'original_hire_date': 'originalHireDate',  # noqa: E501
        'latest_hire_date': 'latestHireDate',  # noqa: E501
        'latest_pay_date': 'latestPayDate',  # noqa: E501
        'days_since_last_pay': 'daysSinceLastPay',  # noqa: E501
        'number_pay_cadence_without_pay': 'numberPayCadenceWithoutPay',  # noqa: E501
        'employment_end_date': 'employmentEndDate',  # noqa: E501
        'employment_duration': 'employmentDuration',  # noqa: E501
        'employer_address': 'employerAddress',  # noqa: E501
        'work_level_code': 'workLevelCode',  # noqa: E501
        'work_level_name': 'workLevelName',  # noqa: E501
        'position_title': 'positionTitle',  # noqa: E501
        'position_duration': 'positionDuration',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, employer_name, employment_status_code, employment_status_name, work_level_status, *args, **kwargs):  # noqa: E501
        """PayrollEmploymentRecord - a model defined in OpenAPI

        Args:
            employer_name (str): Name of the employer as stated by the employer in the payroll system
            employment_status_code (str): 'Status codes: `A` - Active, `NLE` - No Longer Employed, `L` - Leave, `O` - Other'
            employment_status_name (str): 'Status name: `Active`, `No Longer Employed`, `Leave` or `Other`'
            work_level_status (str): The categorized work level status. Enumerations are:  * `Temporary`  * `Seasonal`  * `Retired`  * `Student`  * `Full Time`  * `Part Time`  * `Unspecified`  This is a new field, currently enabled only for testing reports. It will be added for all reports in August 2021. 

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            legal_entity_id (str): Employer identification number (EIN). [optional]  # noqa: E501
            original_hire_date (int): The original hired date of an employee at the company. [optional]  # noqa: E501
            latest_hire_date (int): If an employee leaves the company and returns later, then the employer states the latest hire date at the company. [optional]  # noqa: E501
            latest_pay_date (int): The most recent pay date from an employer. [optional]  # noqa: E501
            days_since_last_pay (int): The number of days since an employee was last paid. [optional]  # noqa: E501
            number_pay_cadence_without_pay (int): The number of pay cadences an employee has not been paid; determined by the pay frequency. [optional]  # noqa: E501
            employment_end_date (int): The date an employee ended their employment at the company. [optional]  # noqa: E501
            employment_duration (str): The length of time an employee has been employed with that employer in ISO 8601 format (eg P1Y6M0D). [optional]  # noqa: E501
            employer_address ([PayrollEmployerAddress]): Array of addresses. [optional]  # noqa: E501
            work_level_code (str): The abbreviate code for the employment level names (workLevelName) that we receive from the employer. [optional]  # noqa: E501
            work_level_name (str): The employment level name is whatever we receive from the employer, such as full time, part time, temp, contractor, and more. [optional]  # noqa: E501
            position_title (str): Employee job title. [optional]  # noqa: E501
            position_duration (str): The length of time an employee has been employed at their current or latest position for this employment in ISO 8601 format (eg P1Y6M0D). [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.employer_name = employer_name
        self.employment_status_code = employment_status_code
        self.employment_status_name = employment_status_name
        self.work_level_status = work_level_status
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, employer_name, employment_status_code, employment_status_name, work_level_status, *args, **kwargs):  # noqa: E501
        """PayrollEmploymentRecord - a model defined in OpenAPI

        Args:
            employer_name (str): Name of the employer as stated by the employer in the payroll system
            employment_status_code (str): 'Status codes: `A` - Active, `NLE` - No Longer Employed, `L` - Leave, `O` - Other'
            employment_status_name (str): 'Status name: `Active`, `No Longer Employed`, `Leave` or `Other`'
            work_level_status (str): The categorized work level status. Enumerations are:  * `Temporary`  * `Seasonal`  * `Retired`  * `Student`  * `Full Time`  * `Part Time`  * `Unspecified`  This is a new field, currently enabled only for testing reports. It will be added for all reports in August 2021. 

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            legal_entity_id (str): Employer identification number (EIN). [optional]  # noqa: E501
            original_hire_date (int): The original hired date of an employee at the company. [optional]  # noqa: E501
            latest_hire_date (int): If an employee leaves the company and returns later, then the employer states the latest hire date at the company. [optional]  # noqa: E501
            latest_pay_date (int): The most recent pay date from an employer. [optional]  # noqa: E501
            days_since_last_pay (int): The number of days since an employee was last paid. [optional]  # noqa: E501
            number_pay_cadence_without_pay (int): The number of pay cadences an employee has not been paid; determined by the pay frequency. [optional]  # noqa: E501
            employment_end_date (int): The date an employee ended their employment at the company. [optional]  # noqa: E501
            employment_duration (str): The length of time an employee has been employed with that employer in ISO 8601 format (eg P1Y6M0D). [optional]  # noqa: E501
            employer_address ([PayrollEmployerAddress]): Array of addresses. [optional]  # noqa: E501
            work_level_code (str): The abbreviate code for the employment level names (workLevelName) that we receive from the employer. [optional]  # noqa: E501
            work_level_name (str): The employment level name is whatever we receive from the employer, such as full time, part time, temp, contractor, and more. [optional]  # noqa: E501
            position_title (str): Employee job title. [optional]  # noqa: E501
            position_duration (str): The length of time an employee has been employed at their current or latest position for this employment in ISO 8601 format (eg P1Y6M0D). [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.employer_name = employer_name
        self.employment_status_code = employment_status_code
        self.employment_status_name = employment_status_name
        self.work_level_status = work_level_status
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
