"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)
from ..model_utils import OpenApiModel
from openapi_client.exceptions import ApiAttributeError


def lazy_import():
    from openapi_client.model.account_details_tx_based import AccountDetailsTxBased
    from openapi_client.model.cash_flow_cash_flow_balance import CashFlowCashFlowBalance
    from openapi_client.model.cash_flow_cash_flow_characteristic import CashFlowCashFlowCharacteristic
    from openapi_client.model.cash_flow_cash_flow_credit import CashFlowCashFlowCredit
    from openapi_client.model.cash_flow_cash_flow_debit import CashFlowCashFlowDebit
    from openapi_client.model.cash_flow_report_account import CashFlowReportAccount
    from openapi_client.model.prequalification_report_account import PrequalificationReportAccount
    from openapi_client.model.prequalification_report_asset_summary import PrequalificationReportAssetSummary
    from openapi_client.model.report_account_position import ReportAccountPosition
    from openapi_client.model.report_transaction import ReportTransaction
    from openapi_client.model.report_transaction_new_tx_based import ReportTransactionNewTxBased
    from openapi_client.model.transactions_report_account import TransactionsReportAccount
    from openapi_client.model.voa_report_account import VOAReportAccount
    from openapi_client.model.voa_with_income_report_account import VOAWithIncomeReportAccount
    from openapi_client.model.voe_transactions_report_account import VOETransactionsReportAccount
    from openapi_client.model.voi_report_account import VOIReportAccount
    from openapi_client.model.voietx_verify_report_account import VOIETXVerifyReportAccount
    from openapi_client.model.voietx_verify_report_income_stream import VOIETXVerifyReportIncomeStream
    globals()['AccountDetailsTxBased'] = AccountDetailsTxBased
    globals()['CashFlowCashFlowBalance'] = CashFlowCashFlowBalance
    globals()['CashFlowCashFlowCharacteristic'] = CashFlowCashFlowCharacteristic
    globals()['CashFlowCashFlowCredit'] = CashFlowCashFlowCredit
    globals()['CashFlowCashFlowDebit'] = CashFlowCashFlowDebit
    globals()['CashFlowReportAccount'] = CashFlowReportAccount
    globals()['PrequalificationReportAccount'] = PrequalificationReportAccount
    globals()['PrequalificationReportAssetSummary'] = PrequalificationReportAssetSummary
    globals()['ReportAccountPosition'] = ReportAccountPosition
    globals()['ReportTransaction'] = ReportTransaction
    globals()['ReportTransactionNewTxBased'] = ReportTransactionNewTxBased
    globals()['TransactionsReportAccount'] = TransactionsReportAccount
    globals()['VOAReportAccount'] = VOAReportAccount
    globals()['VOAWithIncomeReportAccount'] = VOAWithIncomeReportAccount
    globals()['VOETransactionsReportAccount'] = VOETransactionsReportAccount
    globals()['VOIETXVerifyReportAccount'] = VOIETXVerifyReportAccount
    globals()['VOIETXVerifyReportIncomeStream'] = VOIETXVerifyReportIncomeStream
    globals()['VOIReportAccount'] = VOIReportAccount


class ReportInstitutionAccount(ModelComposed):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
        ('misc_deposits',): {
            'max_items': 100,
            'min_items': 0,
        },
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'id': (int,),  # noqa: E501
            'name': (str,),  # noqa: E501
            'number': (str,),  # noqa: E501
            'type': (str,),  # noqa: E501
            'aggregation_status_code': (int,),  # noqa: E501
            'transactions': ([ReportTransactionNewTxBased],),  # noqa: E501
            'owner_name': (str,),  # noqa: E501
            'owner_address': (str,),  # noqa: E501
            'current_balance': (float,),  # noqa: E501
            'available_balance': (float,),  # noqa: E501
            'balance_date': (int,),  # noqa: E501
            'cash_flow_balance': (CashFlowCashFlowBalance,),  # noqa: E501
            'cash_flow_credit': (CashFlowCashFlowCredit,),  # noqa: E501
            'cash_flow_debit': (CashFlowCashFlowDebit,),  # noqa: E501
            'cash_flow_characteristic': (CashFlowCashFlowCharacteristic,),  # noqa: E501
            'balance': (float,),  # noqa: E501
            'average_monthly_balance': (float,),  # noqa: E501
            'tot_number_insufficient_funds_fee_debit_tx_account': (int,),  # noqa: E501
            'tot_number_insufficient_funds_fee_debit_tx_over6_months_account': (int,),  # noqa: E501
            'tot_number_days_since_most_recent_insufficient_funds_fee_debit_tx_account': (int,),  # noqa: E501
            'asset': (PrequalificationReportAssetSummary,),  # noqa: E501
            'details': (AccountDetailsTxBased,),  # noqa: E501
            'tot_number_insufficient_funds_fee_debit_tx_over2_months_account': (int,),  # noqa: E501
            'position': (ReportAccountPosition,),  # noqa: E501
            'income_streams': ([VOIETXVerifyReportIncomeStream],),  # noqa: E501
            'beginning_balance': (float,),  # noqa: E501
            'misc_deposits': ([ReportTransaction],),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'id': 'id',  # noqa: E501
        'name': 'name',  # noqa: E501
        'number': 'number',  # noqa: E501
        'type': 'type',  # noqa: E501
        'aggregation_status_code': 'aggregationStatusCode',  # noqa: E501
        'transactions': 'transactions',  # noqa: E501
        'owner_name': 'ownerName',  # noqa: E501
        'owner_address': 'ownerAddress',  # noqa: E501
        'current_balance': 'currentBalance',  # noqa: E501
        'available_balance': 'availableBalance',  # noqa: E501
        'balance_date': 'balanceDate',  # noqa: E501
        'cash_flow_balance': 'cashFlowBalance',  # noqa: E501
        'cash_flow_credit': 'cashFlowCredit',  # noqa: E501
        'cash_flow_debit': 'cashFlowDebit',  # noqa: E501
        'cash_flow_characteristic': 'cashFlowCharacteristic',  # noqa: E501
        'balance': 'balance',  # noqa: E501
        'average_monthly_balance': 'averageMonthlyBalance',  # noqa: E501
        'tot_number_insufficient_funds_fee_debit_tx_account': 'totNumberInsufficientFundsFeeDebitTxAccount',  # noqa: E501
        'tot_number_insufficient_funds_fee_debit_tx_over6_months_account': 'totNumberInsufficientFundsFeeDebitTxOver6MonthsAccount',  # noqa: E501
        'tot_number_days_since_most_recent_insufficient_funds_fee_debit_tx_account': 'totNumberDaysSinceMostRecentInsufficientFundsFeeDebitTxAccount',  # noqa: E501
        'asset': 'asset',  # noqa: E501
        'details': 'details',  # noqa: E501
        'tot_number_insufficient_funds_fee_debit_tx_over2_months_account': 'totNumberInsufficientFundsFeeDebitTxOver2MonthsAccount',  # noqa: E501
        'position': 'position',  # noqa: E501
        'income_streams': 'incomeStreams',  # noqa: E501
        'beginning_balance': 'beginningBalance',  # noqa: E501
        'misc_deposits': 'miscDeposits',  # noqa: E501
    }

    read_only_vars = {
    }

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """ReportInstitutionAccount - a model defined in OpenAPI

        Keyword Args:
            id (int): The ID of the account
            name (str): The account name from the institution
            number (str): The account number from the institution (all digits except the last four are obfuscated)
            type (str): One of the values from account types
            aggregation_status_code (int): The status of the most recent aggregation attempt
            transactions ([ReportTransactionNewTxBased]): a list of transaction records
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            owner_name (str): The name(s) of the account owner(s). This field is optional. If no owner information is available, this field will not appear in the report.. [optional]  # noqa: E501
            owner_address (str): The mailing address of the account owner(s). This field is optional. If no owner information is available, this field will not appear in the report.. [optional]  # noqa: E501
            current_balance (float): Current balance of the account. [optional]  # noqa: E501
            available_balance (float): The available balance for the account. [optional]  # noqa: E501
            balance_date (int): A timestamp showing when the balance was captured. [optional]  # noqa: E501
            cash_flow_balance (CashFlowCashFlowBalance): [optional]  # noqa: E501
            cash_flow_credit (CashFlowCashFlowCredit): [optional]  # noqa: E501
            cash_flow_debit (CashFlowCashFlowDebit): [optional]  # noqa: E501
            cash_flow_characteristic (CashFlowCashFlowCharacteristic): [optional]  # noqa: E501
            balance (float): The cleared balance of the account as-of `balanceDate`. [optional]  # noqa: E501
            average_monthly_balance (float): The average monthly balance of this account. [optional]  # noqa: E501
            tot_number_insufficient_funds_fee_debit_tx_account (int): The count for the total number of insufficient funds transactions, based on the `fromDate` of the report.. [optional]  # noqa: E501
            tot_number_insufficient_funds_fee_debit_tx_over6_months_account (int): The total number of  insufficient funds fees for the account over six months. [optional]  # noqa: E501
            tot_number_days_since_most_recent_insufficient_funds_fee_debit_tx_account (int): The number of days since the most recent insufficient funds transaction, based on the `fromDate` of the report.. [optional]  # noqa: E501
            asset (PrequalificationReportAssetSummary): [optional]  # noqa: E501
            details (AccountDetailsTxBased): [optional]  # noqa: E501
            tot_number_insufficient_funds_fee_debit_tx_over2_months_account (int): The count for the total number of insufficient funds transactions for the last two months, based on the `fromDate` of the report.. [optional]  # noqa: E501
            position (ReportAccountPosition): [optional]  # noqa: E501
            income_streams ([VOIETXVerifyReportIncomeStream]): A list of income stream records. [optional]  # noqa: E501
            beginning_balance (float): Beginning balance of account per the time period in the report. [optional]  # noqa: E501
            misc_deposits ([ReportTransaction]): A list of miscellaneous deposits. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        constant_args = {
            '_check_type': _check_type,
            '_path_to_item': _path_to_item,
            '_spec_property_naming': _spec_property_naming,
            '_configuration': _configuration,
            '_visited_composed_classes': self._visited_composed_classes,
        }
        composed_info = validate_get_composed_info(
            constant_args, kwargs, self)
        self._composed_instances = composed_info[0]
        self._var_name_to_model_instances = composed_info[1]
        self._additional_properties_model_instances = composed_info[2]
        discarded_args = composed_info[3]

        for var_name, var_value in kwargs.items():
            if var_name in discarded_args and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self._additional_properties_model_instances:
                # discard variable.
                continue
            setattr(self, var_name, var_value)

        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
        '_composed_instances',
        '_var_name_to_model_instances',
        '_additional_properties_model_instances',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """ReportInstitutionAccount - a model defined in OpenAPI

        Keyword Args:
            id (int): The ID of the account
            name (str): The account name from the institution
            number (str): The account number from the institution (all digits except the last four are obfuscated)
            type (str): One of the values from account types
            aggregation_status_code (int): The status of the most recent aggregation attempt
            transactions ([ReportTransactionNewTxBased]): a list of transaction records
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            owner_name (str): The name(s) of the account owner(s). This field is optional. If no owner information is available, this field will not appear in the report.. [optional]  # noqa: E501
            owner_address (str): The mailing address of the account owner(s). This field is optional. If no owner information is available, this field will not appear in the report.. [optional]  # noqa: E501
            current_balance (float): Current balance of the account. [optional]  # noqa: E501
            available_balance (float): The available balance for the account. [optional]  # noqa: E501
            balance_date (int): A timestamp showing when the balance was captured. [optional]  # noqa: E501
            cash_flow_balance (CashFlowCashFlowBalance): [optional]  # noqa: E501
            cash_flow_credit (CashFlowCashFlowCredit): [optional]  # noqa: E501
            cash_flow_debit (CashFlowCashFlowDebit): [optional]  # noqa: E501
            cash_flow_characteristic (CashFlowCashFlowCharacteristic): [optional]  # noqa: E501
            balance (float): The cleared balance of the account as-of `balanceDate`. [optional]  # noqa: E501
            average_monthly_balance (float): The average monthly balance of this account. [optional]  # noqa: E501
            tot_number_insufficient_funds_fee_debit_tx_account (int): The count for the total number of insufficient funds transactions, based on the `fromDate` of the report.. [optional]  # noqa: E501
            tot_number_insufficient_funds_fee_debit_tx_over6_months_account (int): The total number of  insufficient funds fees for the account over six months. [optional]  # noqa: E501
            tot_number_days_since_most_recent_insufficient_funds_fee_debit_tx_account (int): The number of days since the most recent insufficient funds transaction, based on the `fromDate` of the report.. [optional]  # noqa: E501
            asset (PrequalificationReportAssetSummary): [optional]  # noqa: E501
            details (AccountDetailsTxBased): [optional]  # noqa: E501
            tot_number_insufficient_funds_fee_debit_tx_over2_months_account (int): The count for the total number of insufficient funds transactions for the last two months, based on the `fromDate` of the report.. [optional]  # noqa: E501
            position (ReportAccountPosition): [optional]  # noqa: E501
            income_streams ([VOIETXVerifyReportIncomeStream]): A list of income stream records. [optional]  # noqa: E501
            beginning_balance (float): Beginning balance of account per the time period in the report. [optional]  # noqa: E501
            misc_deposits ([ReportTransaction]): A list of miscellaneous deposits. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        constant_args = {
            '_check_type': _check_type,
            '_path_to_item': _path_to_item,
            '_spec_property_naming': _spec_property_naming,
            '_configuration': _configuration,
            '_visited_composed_classes': self._visited_composed_classes,
        }
        composed_info = validate_get_composed_info(
            constant_args, kwargs, self)
        self._composed_instances = composed_info[0]
        self._var_name_to_model_instances = composed_info[1]
        self._additional_properties_model_instances = composed_info[2]
        discarded_args = composed_info[3]

        for var_name, var_value in kwargs.items():
            if var_name in discarded_args and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self._additional_properties_model_instances:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")

    @cached_property
    def _composed_schemas():
        # we need this here to make our import statements work
        # we must store _composed_schemas in here so the code is only run
        # when we invoke this method. If we kept this at the class
        # level we would get an error because the class level
        # code would be run when this module is imported, and these composed
        # classes don't exist yet because their module has not finished
        # loading
        lazy_import()
        return {
          'anyOf': [
          ],
          'allOf': [
              CashFlowReportAccount,
              PrequalificationReportAccount,
              TransactionsReportAccount,
              VOAReportAccount,
              VOAWithIncomeReportAccount,
              VOETransactionsReportAccount,
              VOIETXVerifyReportAccount,
              VOIReportAccount,
          ],
          'oneOf': [
          ],
        }
