"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.base_report_ack_with_portfolio_id import BaseReportAckWithPortfolioId
from openapi_client.model.error_message import ErrorMessage
from openapi_client.model.voa_with_income_report_ack_all_of import VOAWithIncomeReportAckAllOf
from openapi_client.model.voa_with_income_report_constraints_out import VOAWithIncomeReportConstraintsOut
globals()['BaseReportAckWithPortfolioId'] = BaseReportAckWithPortfolioId
globals()['ErrorMessage'] = ErrorMessage
globals()['VOAWithIncomeReportAckAllOf'] = VOAWithIncomeReportAckAllOf
globals()['VOAWithIncomeReportConstraintsOut'] = VOAWithIncomeReportConstraintsOut
from openapi_client.model.voa_with_income_report_ack import VOAWithIncomeReportAck


class TestVOAWithIncomeReportAck(unittest.TestCase):
    """VOAWithIncomeReportAck unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVOAWithIncomeReportAck(self):
        """Test VOAWithIncomeReportAck"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VOAWithIncomeReportAck()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
