"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.verify_assets_api import VerifyAssetsApi  # noqa: E501


class TestVerifyAssetsApi(unittest.TestCase):
    """VerifyAssetsApi unit test stubs"""

    def setUp(self):
        self.api = VerifyAssetsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_generate_prequalification_cra_report(self):
        """Test case for generate_prequalification_cra_report

        Generate Prequalification (CRA) Report  # noqa: E501
        """
        pass

    def test_generate_prequalification_non_cra_report(self):
        """Test case for generate_prequalification_non_cra_report

        Generate Prequalification (Non-CRA) Report  # noqa: E501
        """
        pass

    def test_generate_voa_report(self):
        """Test case for generate_voa_report

        Generate VOA Report  # noqa: E501
        """
        pass

    def test_generate_voa_with_income_report(self):
        """Test case for generate_voa_with_income_report

        Generate VOA With Income Report  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
