"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.account_owner_email import AccountOwnerEmail
globals()['AccountOwnerEmail'] = AccountOwnerEmail
from openapi_client.model.account_owner_emails import AccountOwnerEmails


class TestAccountOwnerEmails(unittest.TestCase):
    """AccountOwnerEmails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountOwnerEmails(self):
        """Test AccountOwnerEmails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountOwnerEmails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
