"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.bank_statements_api import BankStatementsApi  # noqa: E501


class TestBankStatementsApi(unittest.TestCase):
    """BankStatementsApi unit test stubs"""

    def setUp(self):
        self.api = BankStatementsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_generate_statement_report(self):
        """Test case for generate_statement_report

        Generate Statement Report  # noqa: E501
        """
        pass

    def test_get_customer_account_statement(self):
        """Test case for get_customer_account_statement

        Get Customer Account Statement  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
