"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.third_party_access_period import ThirdPartyAccessPeriod


class TestThirdPartyAccessPeriod(unittest.TestCase):
    """ThirdPartyAccessPeriod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testThirdPartyAccessPeriod(self):
        """Test ThirdPartyAccessPeriod"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ThirdPartyAccessPeriod()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
