"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.reports_api import ReportsApi  # noqa: E501


class TestReportsApi(unittest.TestCase):
    """ReportsApi unit test stubs"""

    def setUp(self):
        self.api = ReportsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_report_by_consumer(self):
        """Test case for get_report_by_consumer

        Get Report by Consumer and ID  # noqa: E501
        """
        pass

    def test_get_report_by_customer(self):
        """Test case for get_report_by_customer

        Get Report by Customer and ID  # noqa: E501
        """
        pass

    def test_get_reports_by_consumer_id(self):
        """Test case for get_reports_by_consumer_id

        Get Reports by Consumer ID  # noqa: E501
        """
        pass

    def test_get_reports_by_customer_id(self):
        """Test case for get_reports_by_customer_id

        Get Reports by Customer ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
