"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.cash_flow_transaction_analytics_attributes_last_transaction_date import CashFlowTransactionAnalyticsAttributesLastTransactionDate


class TestCashFlowTransactionAnalyticsAttributesLastTransactionDate(unittest.TestCase):
    """CashFlowTransactionAnalyticsAttributesLastTransactionDate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCashFlowTransactionAnalyticsAttributesLastTransactionDate(self):
        """Test CashFlowTransactionAnalyticsAttributesLastTransactionDate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CashFlowTransactionAnalyticsAttributesLastTransactionDate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
