"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.voi_report_constraints_out import VOIReportConstraintsOut
globals()['VOIReportConstraintsOut'] = VOIReportConstraintsOut
from openapi_client.model.voi_report_ack_all_of import VOIReportAckAllOf


class TestVOIReportAckAllOf(unittest.TestCase):
    """VOIReportAckAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVOIReportAckAllOf(self):
        """Test VOIReportAckAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VOIReportAckAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
