"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.cash_flow_report_constraints_out import CashFlowReportConstraintsOut
globals()['CashFlowReportConstraintsOut'] = CashFlowReportConstraintsOut
from openapi_client.model.cash_flow_report_ack_all_of import CashFlowReportAckAllOf


class TestCashFlowReportAckAllOf(unittest.TestCase):
    """CashFlowReportAckAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCashFlowReportAckAllOf(self):
        """Test CashFlowReportAckAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CashFlowReportAckAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
