"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.report_transaction import ReportTransaction
from openapi_client.model.voi_report_income_stream import VOIReportIncomeStream
globals()['ReportTransaction'] = ReportTransaction
globals()['VOIReportIncomeStream'] = VOIReportIncomeStream
from openapi_client.model.voi_report_account import VOIReportAccount


class TestVOIReportAccount(unittest.TestCase):
    """VOIReportAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVOIReportAccount(self):
        """Test VOIReportAccount"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VOIReportAccount()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
