"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.payroll_employment_history_voe import PayrollEmploymentHistoryVOE
globals()['PayrollEmploymentHistoryVOE'] = PayrollEmploymentHistoryVOE
from openapi_client.model.voe_payroll_report_all_of import VOEPayrollReportAllOf


class TestVOEPayrollReportAllOf(unittest.TestCase):
    """VOEPayrollReportAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVOEPayrollReportAllOf(self):
        """Test VOEPayrollReportAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VOEPayrollReportAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
