"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.base_report_ack import BaseReportAck
from openapi_client.model.cash_flow_report_ack_all_of import CashFlowReportAckAllOf
from openapi_client.model.cash_flow_report_constraints_out import CashFlowReportConstraintsOut
from openapi_client.model.error_message import ErrorMessage
globals()['BaseReportAck'] = BaseReportAck
globals()['CashFlowReportAckAllOf'] = CashFlowReportAckAllOf
globals()['CashFlowReportConstraintsOut'] = CashFlowReportConstraintsOut
globals()['ErrorMessage'] = ErrorMessage
from openapi_client.model.cash_flow_report_ack import CashFlowReportAck


class TestCashFlowReportAck(unittest.TestCase):
    """CashFlowReportAck unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCashFlowReportAck(self):
        """Test CashFlowReportAck"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CashFlowReportAck()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
