"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.cash_flow_analytics_api import CashFlowAnalyticsApi  # noqa: E501


class TestCashFlowAnalyticsApi(unittest.TestCase):
    """CashFlowAnalyticsApi unit test stubs"""

    def setUp(self):
        self.api = CashFlowAnalyticsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_generate_cash_flow_analytics(self):
        """Test case for generate_cash_flow_analytics

        Generate Cash Flow Analytics  # noqa: E501
        """
        pass

    def test_generate_cash_flow_analytics_fcra(self):
        """Test case for generate_cash_flow_analytics_fcra

        Generate Cash Flow Analytics - FCRA  # noqa: E501
        """
        pass

    def test_get_obb_analytics_report(self):
        """Test case for get_obb_analytics_report

        Get OBB Analytics Report  # noqa: E501
        """
        pass

    def test_get_obb_analytics_report_fcra(self):
        """Test case for get_obb_analytics_report_fcra

        Get OBB Analytics Report - FCRA  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
