"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.customers_api import CustomersApi  # noqa: E501


class TestCustomersApi(unittest.TestCase):
    """CustomersApi unit test stubs"""

    def setUp(self):
        self.api = CustomersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_customer(self):
        """Test case for add_customer

        Add Customer  # noqa: E501
        """
        pass

    def test_add_testing_customer(self):
        """Test case for add_testing_customer

        Add Testing Customer  # noqa: E501
        """
        pass

    def test_delete_customer(self):
        """Test case for delete_customer

        Delete Customer by ID  # noqa: E501
        """
        pass

    def test_get_customer(self):
        """Test case for get_customer

        Get Customer by ID  # noqa: E501
        """
        pass

    def test_get_customer_with_app_data(self):
        """Test case for get_customer_with_app_data

        Get Customer With App Data by ID  # noqa: E501
        """
        pass

    def test_get_customers(self):
        """Test case for get_customers

        Get Customers  # noqa: E501
        """
        pass

    def test_modify_customer(self):
        """Test case for modify_customer

        Modify Customer by ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
