"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.account_details_tx_based import AccountDetailsTxBased
from openapi_client.model.prequalification_report_asset_summary import PrequalificationReportAssetSummary
from openapi_client.model.report_account_position import ReportAccountPosition
from openapi_client.model.report_transaction_new_tx_based import ReportTransactionNewTxBased
globals()['AccountDetailsTxBased'] = AccountDetailsTxBased
globals()['PrequalificationReportAssetSummary'] = PrequalificationReportAssetSummary
globals()['ReportAccountPosition'] = ReportAccountPosition
globals()['ReportTransactionNewTxBased'] = ReportTransactionNewTxBased
from openapi_client.model.voa_report_account import VOAReportAccount


class TestVOAReportAccount(unittest.TestCase):
    """VOAReportAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVOAReportAccount(self):
        """Test VOAReportAccount"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VOAReportAccount()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
