"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.report_account_ids import ReportAccountIds
from openapi_client.model.report_custom_fields import ReportCustomFields
from openapi_client.model.voie_with_interview_data import VOIEWithInterviewData
globals()['ReportAccountIds'] = ReportAccountIds
globals()['ReportCustomFields'] = ReportCustomFields
globals()['VOIEWithInterviewData'] = VOIEWithInterviewData
from openapi_client.model.voie_with_tx_verify_report_constraints_out import VOIEWithTXVerifyReportConstraintsOut


class TestVOIEWithTXVerifyReportConstraintsOut(unittest.TestCase):
    """VOIEWithTXVerifyReportConstraintsOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVOIEWithTXVerifyReportConstraintsOut(self):
        """Test VOIEWithTXVerifyReportConstraintsOut"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VOIEWithTXVerifyReportConstraintsOut()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
