"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.cash_flow_analytics_metrics import CashFlowAnalyticsMetrics
from openapi_client.model.obb_current_report_request_details import ObbCurrentReportRequestDetails
from openapi_client.model.obb_data_availability import ObbDataAvailability
globals()['CashFlowAnalyticsMetrics'] = CashFlowAnalyticsMetrics
globals()['ObbCurrentReportRequestDetails'] = ObbCurrentReportRequestDetails
globals()['ObbDataAvailability'] = ObbDataAvailability
from openapi_client.model.cash_flow_analytics_business_summary import CashFlowAnalyticsBusinessSummary


class TestCashFlowAnalyticsBusinessSummary(unittest.TestCase):
    """CashFlowAnalyticsBusinessSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCashFlowAnalyticsBusinessSummary(self):
        """Test CashFlowAnalyticsBusinessSummary"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CashFlowAnalyticsBusinessSummary()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
