"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.child_institution import ChildInstitution
globals()['ChildInstitution'] = ChildInstitution
from openapi_client.model.certified_institution import CertifiedInstitution


class TestCertifiedInstitution(unittest.TestCase):
    """CertifiedInstitution unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCertifiedInstitution(self):
        """Test CertifiedInstitution"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CertifiedInstitution()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
