"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.report_institution import ReportInstitution
globals()['ReportInstitution'] = ReportInstitution
from openapi_client.model.voe_transactions_report_all_of import VOETransactionsReportAllOf


class TestVOETransactionsReportAllOf(unittest.TestCase):
    """VOETransactionsReportAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVOETransactionsReportAllOf(self):
        """Test VOETransactionsReportAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VOETransactionsReportAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
