"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.  # noqa: E501

    The version of the OpenAPI document: 1.13.7
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.portfolio_consumer import PortfolioConsumer
globals()['PortfolioConsumer'] = PortfolioConsumer
from openapi_client.model.portfolio_with_consumer_summary_all_of import PortfolioWithConsumerSummaryAllOf


class TestPortfolioWithConsumerSummaryAllOf(unittest.TestCase):
    """PortfolioWithConsumerSummaryAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPortfolioWithConsumerSummaryAllOf(self):
        """Test PortfolioWithConsumerSummaryAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PortfolioWithConsumerSummaryAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
